# Enable cargo build --fail-on-warnings
# https://www.reddit.com/r/rust/comments/8oz7md/make_cargo_fail_on_warning/e087nj8?utm_source=share&utm_medium=web2x&context=3
[features]
fail-on-warnings = []

[package]
name = "bm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
anyhow = "1.0.42"
ansi_term = "0.12.1"
regex = "1.5.4"